
version: '3.8'

services:
  django:
    build: .
    env_file: .env
    container_name: django_app
    volumes:
      - static_volume:/staticfiles
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/staticfiles
    depends_on:
      - django

volumes:
  static_volume:


