FROM --platform=linux/arm64 nginx:latest

COPY --from=voucherz-app /app/staticfiles /staticfiles

# ローカルの default.conf をイメージ内にコピー
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf


# スクリプトをコンテナにコピー
COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh

# スクリプトに実行権限を付与（必要な場合）
RUN chmod +x /usr/local/bin/wait-for-it.sh


# Entrypoint をスクリプトに変更
ENTRYPOINT ["/usr/local/bin/wait-for-it.sh"]
