# Generated by Django 5.2.4 on 2025-08-17 03:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=255)),
                ('target_product', models.CharField(max_length=255)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('max_issuance', models.IntegerField(blank=True, null=True)),
                ('redeemed_count', models.IntegerField(default=0, editable=False)),
                ('issued_count', models.IntegerField(default=0, editable=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='account.store')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.BigIntegerField()),
                ('coupon_code', models.CharField(editable=False, max_length=6)),
                ('coupon_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('redeemed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(db_column='coupon_id', on_delete=django.db.models.deletion.CASCADE, related_name='coupon_codes', to='coupon.coupon')),
            ],
            options={
                'verbose_name': 'Coupon code',
                'verbose_name_plural': 'Coupon codes',
                'db_table': 'coupon_codes',
                'constraints': [models.UniqueConstraint(fields=('store_id', 'coupon_code'), name='unique_store_couponcode')],
            },
        ),
    ]
